//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotcOnlineDataRepository.WotcServices.Workspace {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentIdentifier", Namespace="http://schemas.datacontract.org/2004/07/WotC.ContentVault")]
    [System.SerializableAttribute()]
    internal partial class ContentIdentifier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ContentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OfficialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OfficialTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ScratchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> ContentID {
            get {
                return this.ContentIDField;
            }
            set {
                if ((this.ContentIDField.Equals(value) != true)) {
                    this.ContentIDField = value;
                    this.RaisePropertyChanged("ContentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Official {
            get {
                return this.OfficialField;
            }
            set {
                if ((this.OfficialField.Equals(value) != true)) {
                    this.OfficialField = value;
                    this.RaisePropertyChanged("Official");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> OfficialTypeID {
            get {
                return this.OfficialTypeIDField;
            }
            set {
                if ((this.OfficialTypeIDField.Equals(value) != true)) {
                    this.OfficialTypeIDField = value;
                    this.RaisePropertyChanged("OfficialTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> ScratchID {
            get {
                return this.ScratchIDField;
            }
            set {
                if ((this.ScratchIDField.Equals(value) != true)) {
                    this.ScratchIDField = value;
                    this.RaisePropertyChanged("ScratchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int TypeID {
            get {
                return this.TypeIDField;
            }
            set {
                if ((this.TypeIDField.Equals(value) != true)) {
                    this.TypeIDField = value;
                    this.RaisePropertyChanged("TypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RulesEngineUpdate", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.MakeChoice))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.EquipItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.LoadCampaignSettings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineDataRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.GetTextStrings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.GetPortrait))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.ReloadAll))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.SetPortrait))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.SaveCharacter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.AutoCompleteCharacter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.AddItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.ManageJournalEntry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.SetLevel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.SetCurrency))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.SetGrabBag))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.SetTextString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.SetAllAbilityScores))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.SetAbilityScoreBase))]
    internal partial class RulesEngineUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MakeChoice", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class MakeChoice : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToLoseIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ChoiceID {
            get {
                return this.ChoiceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ChoiceIDField, value) != true)) {
                    this.ChoiceIDField = value;
                    this.RaisePropertyChanged("ChoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ToLoseID {
            get {
                return this.ToLoseIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ToLoseIDField, value) != true)) {
                    this.ToLoseIDField = value;
                    this.RaisePropertyChanged("ToLoseID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquipItem", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class EquipItem : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> VersatileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<bool> Versatile {
            get {
                return this.VersatileField;
            }
            set {
                if ((this.VersatileField.Equals(value) != true)) {
                    this.VersatileField = value;
                    this.RaisePropertyChanged("Versatile");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadCampaignSettings", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class LoadCampaignSettings : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WotcOnlineDataRepository.WotcServices.Workspace.ContentIdentifier CampaignIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal WotcOnlineDataRepository.WotcServices.Workspace.ContentIdentifier CampaignID {
            get {
                return this.CampaignIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignIDField, value) != true)) {
                    this.CampaignIDField = value;
                    this.RaisePropertyChanged("CampaignID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RulesEngineDataRequest", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.GetTextStrings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.GetPortrait))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.ReloadAll))]
    internal partial class RulesEngineDataRequest : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTextStrings", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class GetTextStrings : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineDataRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPortrait", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class GetPortrait : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineDataRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReloadAll", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class ReloadAll : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineDataRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetPortrait", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class SetPortrait : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExplicitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WotcOnlineDataRepository.WotcServices.Workspace.ContentIdentifier PortraitIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Explicit {
            get {
                return this.ExplicitField;
            }
            set {
                if ((this.ExplicitField.Equals(value) != true)) {
                    this.ExplicitField = value;
                    this.RaisePropertyChanged("Explicit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal WotcOnlineDataRepository.WotcServices.Workspace.ContentIdentifier PortraitID {
            get {
                return this.PortraitIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PortraitIDField, value) != true)) {
                    this.PortraitIDField = value;
                    this.RaisePropertyChanged("PortraitID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveCharacter", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class SaveCharacter : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutoCompleteCharacter", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class AutoCompleteCharacter : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EquipmentOnlyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool EquipmentOnly {
            get {
                return this.EquipmentOnlyField;
            }
            set {
                if ((this.EquipmentOnlyField.Equals(value) != true)) {
                    this.EquipmentOnlyField = value;
                    this.RaisePropertyChanged("EquipmentOnly");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddItem", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class AddItem : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseItemTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnchantNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SubtractMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValuePercentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string BaseItemName {
            get {
                return this.BaseItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseItemNameField, value) != true)) {
                    this.BaseItemNameField = value;
                    this.RaisePropertyChanged("BaseItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string BaseItemType {
            get {
                return this.BaseItemTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseItemTypeField, value) != true)) {
                    this.BaseItemTypeField = value;
                    this.RaisePropertyChanged("BaseItemType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EnchantName {
            get {
                return this.EnchantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EnchantNameField, value) != true)) {
                    this.EnchantNameField = value;
                    this.RaisePropertyChanged("EnchantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool SubtractMoney {
            get {
                return this.SubtractMoneyField;
            }
            set {
                if ((this.SubtractMoneyField.Equals(value) != true)) {
                    this.SubtractMoneyField = value;
                    this.RaisePropertyChanged("SubtractMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int ValuePercent {
            get {
                return this.ValuePercentField;
            }
            set {
                if ((this.ValuePercentField.Equals(value) != true)) {
                    this.ValuePercentField = value;
                    this.RaisePropertyChanged("ValuePercent");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManageJournalEntry", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class ManageJournalEntry : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GPDeltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GPStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GPTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelAtEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TreasureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPGainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPTotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string GPDelta {
            get {
                return this.GPDeltaField;
            }
            set {
                if ((object.ReferenceEquals(this.GPDeltaField, value) != true)) {
                    this.GPDeltaField = value;
                    this.RaisePropertyChanged("GPDelta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string GPStart {
            get {
                return this.GPStartField;
            }
            set {
                if ((object.ReferenceEquals(this.GPStartField, value) != true)) {
                    this.GPStartField = value;
                    this.RaisePropertyChanged("GPStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string GPTotal {
            get {
                return this.GPTotalField;
            }
            set {
                if ((object.ReferenceEquals(this.GPTotalField, value) != true)) {
                    this.GPTotalField = value;
                    this.RaisePropertyChanged("GPTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LevelAtEnd {
            get {
                return this.LevelAtEndField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelAtEndField, value) != true)) {
                    this.LevelAtEndField = value;
                    this.RaisePropertyChanged("LevelAtEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((this.ModeField.Equals(value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Treasure {
            get {
                return this.TreasureField;
            }
            set {
                if ((object.ReferenceEquals(this.TreasureField, value) != true)) {
                    this.TreasureField = value;
                    this.RaisePropertyChanged("Treasure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string XPGain {
            get {
                return this.XPGainField;
            }
            set {
                if ((object.ReferenceEquals(this.XPGainField, value) != true)) {
                    this.XPGainField = value;
                    this.RaisePropertyChanged("XPGain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string XPStart {
            get {
                return this.XPStartField;
            }
            set {
                if ((object.ReferenceEquals(this.XPStartField, value) != true)) {
                    this.XPStartField = value;
                    this.RaisePropertyChanged("XPStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string XPTotal {
            get {
                return this.XPTotalField;
            }
            set {
                if ((object.ReferenceEquals(this.XPTotalField, value) != true)) {
                    this.XPTotalField = value;
                    this.RaisePropertyChanged("XPTotal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetLevel", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class SetLevel : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetCurrency", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class SetCurrency : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AutoGoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<double> BankedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<double> CarriedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool AutoGold {
            get {
                return this.AutoGoldField;
            }
            set {
                if ((this.AutoGoldField.Equals(value) != true)) {
                    this.AutoGoldField = value;
                    this.RaisePropertyChanged("AutoGold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<double> Banked {
            get {
                return this.BankedField;
            }
            set {
                if ((object.ReferenceEquals(this.BankedField, value) != true)) {
                    this.BankedField = value;
                    this.RaisePropertyChanged("Banked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<double> Carried {
            get {
                return this.CarriedField;
            }
            set {
                if ((object.ReferenceEquals(this.CarriedField, value) != true)) {
                    this.CarriedField = value;
                    this.RaisePropertyChanged("Carried");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetGrabBag", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class SetGrabBag : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RemoveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ElementID {
            get {
                return this.ElementIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementIDField, value) != true)) {
                    this.ElementIDField = value;
                    this.RaisePropertyChanged("ElementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Remove {
            get {
                return this.RemoveField;
            }
            set {
                if ((this.RemoveField.Equals(value) != true)) {
                    this.RemoveField = value;
                    this.RaisePropertyChanged("Remove");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetTextString", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class SetTextString : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetAllAbilityScores", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class SetAllAbilityScores : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> ValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Collections.Generic.List<int> Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetAbilityScoreBase", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class SetAbilityScoreBase : WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharacterState", Namespace="http://schemas.datacontract.org/2004/07/WotC.CharBuilder.Web")]
    [System.SerializableAttribute()]
    internal partial class CharacterState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RawDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string RawData {
            get {
                return this.RawDataField;
            }
            set {
                if ((object.ReferenceEquals(this.RawDataField, value) != true)) {
                    this.RawDataField = value;
                    this.RaisePropertyChanged("RawData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/WotC.ContentManagement")]
    [System.SerializableAttribute()]
    internal partial class ContentNotFoundFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WotcOnlineDataRepository.WotcServices.Workspace.ContentIdentifier IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OwnerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal WotcOnlineDataRepository.WotcServices.Workspace.ContentIdentifier ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid OwnerID {
            get {
                return this.OwnerIDField;
            }
            set {
                if ((this.OwnerIDField.Equals(value) != true)) {
                    this.OwnerIDField = value;
                    this.RaisePropertyChanged("OwnerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionExpiredFault", Namespace="http://schemas.datacontract.org/2004/07/WotC.WebServiceUtilities.Server")]
    [System.SerializableAttribute()]
    internal partial class SessionExpiredFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="WotcServices.Workspace.ID20WorkspaceService")]
    internal interface ID20WorkspaceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ID20WorkspaceService/Apply", ReplyAction="urn:ID20WorkspaceService/ApplyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.ContentNotFoundFault), Action="urn:ID20WorkspaceService/ApplyContentNotFoundFaultFault", Name="ContentNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/WotC.ContentManagement")]
        [System.ServiceModel.FaultContractAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.SessionExpiredFault), Action="urn:ID20WorkspaceService/ApplySessionExpiredFaultFault", Name="SessionExpiredFault", Namespace="http://schemas.datacontract.org/2004/07/WotC.WebServiceUtilities.Server")]
        WotcOnlineDataRepository.WotcServices.Workspace.ApplyResponse Apply(WotcOnlineDataRepository.WotcServices.Workspace.ApplyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ID20WorkspaceService/Apply", ReplyAction="urn:ID20WorkspaceService/ApplyResponse")]
        System.IAsyncResult BeginApply(WotcOnlineDataRepository.WotcServices.Workspace.ApplyRequest request, System.AsyncCallback callback, object asyncState);
        
        WotcOnlineDataRepository.WotcServices.Workspace.ApplyResponse EndApply(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ID20WorkspaceService/GetClientRulesElementData", ReplyAction="urn:ID20WorkspaceService/GetClientRulesElementDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.SessionExpiredFault), Action="urn:ID20WorkspaceService/GetClientRulesElementDataSessionExpiredFaultFault", Name="SessionExpiredFault", Namespace="http://schemas.datacontract.org/2004/07/WotC.WebServiceUtilities.Server")]
        WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataResponse GetClientRulesElementData(WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ID20WorkspaceService/GetClientRulesElementData", ReplyAction="urn:ID20WorkspaceService/GetClientRulesElementDataResponse")]
        System.IAsyncResult BeginGetClientRulesElementData(WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataRequest request, System.AsyncCallback callback, object asyncState);
        
        WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataResponse EndGetClientRulesElementData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ID20WorkspaceService/Login", ReplyAction="urn:ID20WorkspaceService/LoginResponse")]
        WotcOnlineDataRepository.WotcServices.Workspace.LoginResponse Login(WotcOnlineDataRepository.WotcServices.Workspace.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ID20WorkspaceService/Login", ReplyAction="urn:ID20WorkspaceService/LoginResponse")]
        System.IAsyncResult BeginLogin(WotcOnlineDataRepository.WotcServices.Workspace.LoginRequest request, System.AsyncCallback callback, object asyncState);
        
        WotcOnlineDataRepository.WotcServices.Workspace.LoginResponse EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ID20WorkspaceService/PreloadClientRulesElementData", ReplyAction="urn:ID20WorkspaceService/PreloadClientRulesElementDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WotcOnlineDataRepository.WotcServices.Workspace.SessionExpiredFault), Action="urn:ID20WorkspaceService/PreloadClientRulesElementDataSessionExpiredFaultFault", Name="SessionExpiredFault", Namespace="http://schemas.datacontract.org/2004/07/WotC.WebServiceUtilities.Server")]
        WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataResponse PreloadClientRulesElementData(WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ID20WorkspaceService/PreloadClientRulesElementData", ReplyAction="urn:ID20WorkspaceService/PreloadClientRulesElementDataResponse")]
        System.IAsyncResult BeginPreloadClientRulesElementData(WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataRequest request, System.AsyncCallback callback, object asyncState);
        
        WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataResponse EndPreloadClientRulesElementData(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Apply", WrapperNamespace="", IsWrapped=true)]
    internal partial class ApplyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WotcOnlineDataRepository.WotcServices.Workspace.ContentIdentifier characterID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public System.Collections.Generic.List<WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate> updates;
        
        public ApplyRequest() {
        }
        
        public ApplyRequest(WotcOnlineDataRepository.WotcServices.Workspace.ContentIdentifier characterID, System.Collections.Generic.List<WotcOnlineDataRepository.WotcServices.Workspace.RulesEngineUpdate> updates) {
            this.characterID = characterID;
            this.updates = updates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyResponse", WrapperNamespace="", IsWrapped=true)]
    internal partial class ApplyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WotcOnlineDataRepository.WotcServices.Workspace.CharacterState ApplyResult;
        
        public ApplyResponse() {
        }
        
        public ApplyResponse(WotcOnlineDataRepository.WotcServices.Workspace.CharacterState ApplyResult) {
            this.ApplyResult = ApplyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientRulesElementData", WrapperNamespace="", IsWrapped=true)]
    internal partial class GetClientRulesElementDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public System.Collections.Generic.List<string> ids;
        
        public GetClientRulesElementDataRequest() {
        }
        
        public GetClientRulesElementDataRequest(System.Collections.Generic.List<string> ids) {
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientRulesElementDataResponse", WrapperNamespace="", IsWrapped=true)]
    internal partial class GetClientRulesElementDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public System.Collections.Generic.List<string> GetClientRulesElementDataResult;
        
        public GetClientRulesElementDataResponse() {
        }
        
        public GetClientRulesElementDataResponse(System.Collections.Generic.List<string> GetClientRulesElementDataResult) {
            this.GetClientRulesElementDataResult = GetClientRulesElementDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="", IsWrapped=true)]
    internal partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public byte[] password;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string userName, byte[] password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="", IsWrapped=true)]
    internal partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool LoginResult;
        
        public LoginResponse() {
        }
        
        public LoginResponse(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PreloadClientRulesElementData", WrapperNamespace="", IsWrapped=true)]
    internal partial class PreloadClientRulesElementDataRequest {
        
        public PreloadClientRulesElementDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PreloadClientRulesElementDataResponse", WrapperNamespace="", IsWrapped=true)]
    internal partial class PreloadClientRulesElementDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public System.Collections.Generic.List<string> PreloadClientRulesElementDataResult;
        
        public PreloadClientRulesElementDataResponse() {
        }
        
        public PreloadClientRulesElementDataResponse(System.Collections.Generic.List<string> PreloadClientRulesElementDataResult) {
            this.PreloadClientRulesElementDataResult = PreloadClientRulesElementDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ID20WorkspaceServiceChannel : WotcOnlineDataRepository.WotcServices.Workspace.ID20WorkspaceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ApplyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ApplyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WotcOnlineDataRepository.WotcServices.Workspace.ApplyResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WotcOnlineDataRepository.WotcServices.Workspace.ApplyResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class GetClientRulesElementDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetClientRulesElementDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WotcOnlineDataRepository.WotcServices.Workspace.LoginResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WotcOnlineDataRepository.WotcServices.Workspace.LoginResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class PreloadClientRulesElementDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PreloadClientRulesElementDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class D20WorkspaceServiceClient : System.ServiceModel.ClientBase<WotcOnlineDataRepository.WotcServices.Workspace.ID20WorkspaceService>, WotcOnlineDataRepository.WotcServices.Workspace.ID20WorkspaceService {
        
        private BeginOperationDelegate onBeginApplyDelegate;
        
        private EndOperationDelegate onEndApplyDelegate;
        
        private System.Threading.SendOrPostCallback onApplyCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetClientRulesElementDataDelegate;
        
        private EndOperationDelegate onEndGetClientRulesElementDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetClientRulesElementDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginPreloadClientRulesElementDataDelegate;
        
        private EndOperationDelegate onEndPreloadClientRulesElementDataDelegate;
        
        private System.Threading.SendOrPostCallback onPreloadClientRulesElementDataCompletedDelegate;
        
        public D20WorkspaceServiceClient() {
        }
        
        public D20WorkspaceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public D20WorkspaceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public D20WorkspaceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public D20WorkspaceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ApplyCompletedEventArgs> ApplyCompleted;
        
        public event System.EventHandler<GetClientRulesElementDataCompletedEventArgs> GetClientRulesElementDataCompleted;
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<PreloadClientRulesElementDataCompletedEventArgs> PreloadClientRulesElementDataCompleted;
        
        public WotcOnlineDataRepository.WotcServices.Workspace.ApplyResponse Apply(WotcOnlineDataRepository.WotcServices.Workspace.ApplyRequest request) {
            return base.Channel.Apply(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginApply(WotcOnlineDataRepository.WotcServices.Workspace.ApplyRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginApply(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WotcOnlineDataRepository.WotcServices.Workspace.ApplyResponse EndApply(System.IAsyncResult result) {
            return base.Channel.EndApply(result);
        }
        
        private System.IAsyncResult OnBeginApply(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WotcOnlineDataRepository.WotcServices.Workspace.ApplyRequest request = ((WotcOnlineDataRepository.WotcServices.Workspace.ApplyRequest)(inValues[0]));
            return this.BeginApply(request, callback, asyncState);
        }
        
        private object[] OnEndApply(System.IAsyncResult result) {
            WotcOnlineDataRepository.WotcServices.Workspace.ApplyResponse retVal = this.EndApply(result);
            return new object[] {
                    retVal};
        }
        
        private void OnApplyCompleted(object state) {
            if ((this.ApplyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ApplyCompleted(this, new ApplyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ApplyAsync(WotcOnlineDataRepository.WotcServices.Workspace.ApplyRequest request) {
            this.ApplyAsync(request, null);
        }
        
        public void ApplyAsync(WotcOnlineDataRepository.WotcServices.Workspace.ApplyRequest request, object userState) {
            if ((this.onBeginApplyDelegate == null)) {
                this.onBeginApplyDelegate = new BeginOperationDelegate(this.OnBeginApply);
            }
            if ((this.onEndApplyDelegate == null)) {
                this.onEndApplyDelegate = new EndOperationDelegate(this.OnEndApply);
            }
            if ((this.onApplyCompletedDelegate == null)) {
                this.onApplyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnApplyCompleted);
            }
            base.InvokeAsync(this.onBeginApplyDelegate, new object[] {
                        request}, this.onEndApplyDelegate, this.onApplyCompletedDelegate, userState);
        }
        
        public WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataResponse GetClientRulesElementData(WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataRequest request) {
            return base.Channel.GetClientRulesElementData(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetClientRulesElementData(WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetClientRulesElementData(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataResponse EndGetClientRulesElementData(System.IAsyncResult result) {
            return base.Channel.EndGetClientRulesElementData(result);
        }
        
        private System.IAsyncResult OnBeginGetClientRulesElementData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataRequest request = ((WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataRequest)(inValues[0]));
            return this.BeginGetClientRulesElementData(request, callback, asyncState);
        }
        
        private object[] OnEndGetClientRulesElementData(System.IAsyncResult result) {
            WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataResponse retVal = this.EndGetClientRulesElementData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetClientRulesElementDataCompleted(object state) {
            if ((this.GetClientRulesElementDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetClientRulesElementDataCompleted(this, new GetClientRulesElementDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetClientRulesElementDataAsync(WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataRequest request) {
            this.GetClientRulesElementDataAsync(request, null);
        }
        
        public void GetClientRulesElementDataAsync(WotcOnlineDataRepository.WotcServices.Workspace.GetClientRulesElementDataRequest request, object userState) {
            if ((this.onBeginGetClientRulesElementDataDelegate == null)) {
                this.onBeginGetClientRulesElementDataDelegate = new BeginOperationDelegate(this.OnBeginGetClientRulesElementData);
            }
            if ((this.onEndGetClientRulesElementDataDelegate == null)) {
                this.onEndGetClientRulesElementDataDelegate = new EndOperationDelegate(this.OnEndGetClientRulesElementData);
            }
            if ((this.onGetClientRulesElementDataCompletedDelegate == null)) {
                this.onGetClientRulesElementDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetClientRulesElementDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetClientRulesElementDataDelegate, new object[] {
                        request}, this.onEndGetClientRulesElementDataDelegate, this.onGetClientRulesElementDataCompletedDelegate, userState);
        }
        
        public WotcOnlineDataRepository.WotcServices.Workspace.LoginResponse Login(WotcOnlineDataRepository.WotcServices.Workspace.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLogin(WotcOnlineDataRepository.WotcServices.Workspace.LoginRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WotcOnlineDataRepository.WotcServices.Workspace.LoginResponse EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WotcOnlineDataRepository.WotcServices.Workspace.LoginRequest request = ((WotcOnlineDataRepository.WotcServices.Workspace.LoginRequest)(inValues[0]));
            return this.BeginLogin(request, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            WotcOnlineDataRepository.WotcServices.Workspace.LoginResponse retVal = this.EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(WotcOnlineDataRepository.WotcServices.Workspace.LoginRequest request) {
            this.LoginAsync(request, null);
        }
        
        public void LoginAsync(WotcOnlineDataRepository.WotcServices.Workspace.LoginRequest request, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        request}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        public WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataResponse PreloadClientRulesElementData(WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataRequest request) {
            return base.Channel.PreloadClientRulesElementData(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPreloadClientRulesElementData(WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPreloadClientRulesElementData(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataResponse EndPreloadClientRulesElementData(System.IAsyncResult result) {
            return base.Channel.EndPreloadClientRulesElementData(result);
        }
        
        private System.IAsyncResult OnBeginPreloadClientRulesElementData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataRequest request = ((WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataRequest)(inValues[0]));
            return this.BeginPreloadClientRulesElementData(request, callback, asyncState);
        }
        
        private object[] OnEndPreloadClientRulesElementData(System.IAsyncResult result) {
            WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataResponse retVal = this.EndPreloadClientRulesElementData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPreloadClientRulesElementDataCompleted(object state) {
            if ((this.PreloadClientRulesElementDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PreloadClientRulesElementDataCompleted(this, new PreloadClientRulesElementDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PreloadClientRulesElementDataAsync(WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataRequest request) {
            this.PreloadClientRulesElementDataAsync(request, null);
        }
        
        public void PreloadClientRulesElementDataAsync(WotcOnlineDataRepository.WotcServices.Workspace.PreloadClientRulesElementDataRequest request, object userState) {
            if ((this.onBeginPreloadClientRulesElementDataDelegate == null)) {
                this.onBeginPreloadClientRulesElementDataDelegate = new BeginOperationDelegate(this.OnBeginPreloadClientRulesElementData);
            }
            if ((this.onEndPreloadClientRulesElementDataDelegate == null)) {
                this.onEndPreloadClientRulesElementDataDelegate = new EndOperationDelegate(this.OnEndPreloadClientRulesElementData);
            }
            if ((this.onPreloadClientRulesElementDataCompletedDelegate == null)) {
                this.onPreloadClientRulesElementDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPreloadClientRulesElementDataCompleted);
            }
            base.InvokeAsync(this.onBeginPreloadClientRulesElementDataDelegate, new object[] {
                        request}, this.onEndPreloadClientRulesElementDataDelegate, this.onPreloadClientRulesElementDataCompletedDelegate, userState);
        }
    }
}
